# Generated by Django 4.0.4 on 2023-05-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bitchdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=22)),
                ('bass', models.IntegerField()),
                ('bbooms', models.IntegerField()),
                ('pussytype', models.CharField(max_length=10)),
            ],
        ),
    ]
